[project]
name = "job-finder-saas-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
    "langchain>=1.2.10",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
